export const operatorsAny = {
  eq: null,
  ne: null,
  gte: null,
  gt: null,
  lte: null,
  lt: null,
  not: null,
  is: [],
  in: [],
  notIn: [],
  between: [],
  notBetween: [],
};

export const operatorsString = {
  like: null,
  notLike: null,
  iLike: null,
  notILike: null,
  startsWith: null,
  endsWith: null,
  substring: null,
  regexp: null,
  notRegexp: null,
  iRegexp: null,
  notIRegexp: null,
  overlap: [],
  contains: [],
  contained: [],
  adjacent: [],
  strictLeft: [],
  strictRight: [],
};
